"""first init db

Revision ID: 48c47b256e6d
Revises: 
Create Date: 2017-05-23 21:47:59.482981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c47b256e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('Q_ID', sa.Integer(), nullable=True),
    sa.Column('Select', sa.String(length=64), nullable=True),
    sa.Column('mark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Stem', sa.Text(), nullable=True),
    sa.Column('Select_1', sa.Text(), nullable=True),
    sa.Column('Select_2', sa.Text(), nullable=True),
    sa.Column('Select_3', sa.Text(), nullable=True),
    sa.Column('Select_4', sa.Text(), nullable=True),
    sa.Column('Select_Right', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('question')
    op.drop_table('marks_record')
    # ### end Alembic commands ###
