"""first init db

Revision ID: 7bbc2ca8bb74
Revises: 48c47b256e6d
Create Date: 2017-05-29 21:56:01.944890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbc2ca8bb74'
down_revision = '48c47b256e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('done', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('list', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'list')
    op.drop_column('question', 'done')
    # ### end Alembic commands ###
