"""first init db

Revision ID: db169b888d81
Revises: 7bbc2ca8bb74
Create Date: 2017-05-29 23:43:01.099822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db169b888d81'
down_revision = '7bbc2ca8bb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'done')
    op.drop_column('question', 'list')
    op.add_column('users', sa.Column('done', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('list', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'list')
    op.drop_column('users', 'done')
    op.add_column('question', sa.Column('list', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('question', sa.Column('done', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
